import type { GatsbyConfig } from "gatsby"

const config: GatsbyConfig = {
  jsxRuntime: "automatic",
  siteMetadata: {
    title: `My Gatsby Site`,
    description: "generated by create yamada app",
    siteUrl: `https://www.yourdomain.tld`,
  },
  // More easily incorporate content into your pages through automatic TypeScript type generation and better GraphQL IntelliSense.
  // If you use VSCode you can also use the GraphQL plugin
  // Learn more at: https://gatsby.dev/graphql-typegen
  graphqlTypegen: true,
  plugins: [
    {
      resolve: "gatsby-plugin-manifest",
      options: {
        icon: "src/images/favicon.svg",
      },
    },
  ],
}

export default config
