codecov:
  require_ci_to_pass: false
  bot: hirotomoyamada
  ci:
    - github-actions

coverage:
  range: 75..95
  status:
    project: false
    patch: false

comment:
  layout: "reach, diff, files, components"
  behavior: default
  require_changes: false

github_checks:
  annotations: false
