import { defineComponentSlotStyle } from "../../core"

export const polarChartStyle = defineComponentSlotStyle({
  base: {
    activeDot: {
      fill: "{active-dot-fill}",
      r: "{active-dot-r}",
      stroke: "{active-dot-stroke}",
      strokeWidth: "{active-dot-stroke-width}",
    },
    angleAxis: {},
    angleAxisLabel: {
      color: "{angle-axis-text-color}",
      fill: "{angle-axis-text-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    angleAxisLine: {
      color: "{angle-axis-text-color}",
      fill: "transparent",
      stroke: "{angle-axis-line-stroke}",
      strokeWidth: "{angle-axis-line-stroke-width}",
    },
    angleAxisTick: {
      color: "{angle-axis-text-color}",
      fill: "{angle-axis-text-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    angleAxisTickLine: {
      color: "{angle-axis-text-color}",
      stroke: "{angle-axis-line-stroke}",
      strokeWidth: "{angle-axis-line-stroke-width}",
    },
    dot: {
      fill: "{dot-fill}",
      r: "{dot-r}",
      stroke: "{dot-stroke}",
      strokeWidth: "{dot-stroke-width}",
    },
    grid: { stroke: "{grid-stroke}" },
    label: {
      _inactive: { opacity: "{inactive-label-opacity}" },
      color: "{label-color}",
      fill: "{label-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    labelLine: {
      _inactive: { opacity: "{inactive-label-line-opacity}" },
      stroke: "{label-line-stroke}",
      strokeWidth: "{label-line-stroke-width}",
    },
    labelList: {
      color: "{label-color}",
      fill: "{label-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    pie: {},
    radar: {
      "&:has(path[data-inactive])": {
        opacity: "{inactive-radar-opacity}",
      },
      color: "{radar-color}",
      fill: "{radar-stroke}",
      fillOpacity: "{radar-fill-opacity}",
      stroke: "{radar-stroke}",
      strokeWidth: "{radar-stroke-width}",
    },
    radial: {},
    radialBackground: {
      color: "{radial-background-color}",
      fill: "{radial-background-fill}",
      stroke: "{radial-background-stroke}",
      strokeWidth: "{radial-background-stroke-width}",
    },
    radiusAxis: {},
    radiusAxisLabel: {
      color: "{radius-axis-text-color}",
      fill: "{radius-axis-text-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    radiusAxisLine: {
      color: "{radius-axis-text-color}",
      stroke: "{radius-axis-line-stroke}",
      strokeWidth: "{radius-axis-line-stroke-width}",
    },
    radiusAxisTick: {
      color: "{radius-axis-text-color}",
      fill: "{radius-axis-text-fill}",
      fontSize: "xs",
      fontWeight: "medium",
    },
    radiusAxisTickLine: {
      color: "{radius-axis-text-color}",
      stroke: "{radius-axis-line-stroke}",
      strokeWidth: "{radius-axis-line-stroke-width}",
    },
    root: {
      "--active-dot-fill": "{radar-color}",
      "--active-dot-r": "4",
      "--active-dot-stroke": "{radar-color}",
      "--active-dot-stroke-width": "0",
      "--angle-axis-line-stroke": "currentColor",
      "--angle-axis-line-stroke-width": "1",
      "--angle-axis-text-color": "colors.fg.muted",
      "--angle-axis-text-fill": "currentColor",
      "--dot-fill": "{radar-stroke}",
      "--dot-r": "4",
      "--dot-stroke": "{radar-stroke}",
      "--dot-stroke-width": "0",
      "--grid-stroke": "colors.border",
      "--inactive-label-line-opacity": "0.4",
      "--inactive-label-opacity": "0.4",
      "--inactive-radar-opacity": "0.4",
      "--inactive-sector-opacity": "0.4",
      "--label-color": "colors.fg.muted",
      "--label-fill": "currentColor",
      "--label-line-stroke": "colors.fg.muted",
      "--label-line-stroke-width": "1",
      "--radar-color": "colorScheme.solid",
      "--radar-fill-opacity": "0.4",
      "--radar-stroke": "currentColor",
      "--radar-stroke-width": "2",
      "--radial-background-color": "colors.bg.subtle",
      "--radial-background-fill": "currentColor",
      "--radial-background-stroke": "currentColor",
      "--radial-background-stroke-width": "0",
      "--radius-axis-line-stroke": "colors.border",
      "--radius-axis-line-stroke-width": "1",
      "--radius-axis-text-color": "colors.fg.muted",
      "--radius-axis-text-fill": "currentColor",
      "--sector-color": "colorScheme.solid",
      "--sector-fill": "currentColor",
      "--sector-stroke": "colors.bg",
      "--sector-stroke-width": "2",
    },
    sector: {
      _inactive: { opacity: "{inactive-sector-opacity}" },
      color: "{sector-color}",
      fill: "{sector-fill}",
      stroke: "{sector-stroke}",
      strokeWidth: "{sector-stroke-width}",
    },
  },
})

export type PolarChartStyle = typeof polarChartStyle
