export const TEAM = {
  MAINTAINERS: [
    {
      id: "hirotomoyamada",
      name: { en: "Hirotomo Yamada", ja: "Hirotomo Yamada" },
      icon: "https://avatars.githubusercontent.com/u/84060430?v=4",
      github: "https://github.com/hirotomoyamada",
      twitter: "https://twitter.com/hirotomoyamada",
      description: {
        en: "Developer of Yamada UI. Designer, design system and UI engineer.",
        ja: "Yamada UIの開発者。デザイナー・デザインシステムおよびUIエンジニア。",
      },
    },
    {
      id: "108yen",
      name: { en: "Kazuki Shirai", ja: "Kazuki Shirai" },
      icon: "https://avatars.githubusercontent.com/u/9676316?v=4",
      github: "https://github.com/108yen",
      twitter: "https://twitter.com/108yen___",
      description: {
        en: "Security risk assessment, Web engineer.",
        ja: "セキュリティリスクアセスメント。Webエンジニア。",
      },
    },
    {
      id: "illionillion",
      name: { en: "Yuto Ichinose", ja: "Ichinose Yuto" },
      icon: "https://avatars.githubusercontent.com/u/60034520?v=4",
      github: "https://github.com/illionillion",
      twitter: "https://twitter.com/dimyasvariant",
      description: {
        en: "Web engineer, a university student.",
        ja: "Webエンジニア。大学生。",
      },
    },
    {
      id: "nakayan5",
      name: { en: "Tomoya Nakamura", ja: "Tomoya Nakamura" },
      icon: "https://avatars.githubusercontent.com/u/63556889?v=4",
      github: "https://github.com/nakayan5",
      twitter: "https://twitter.com/nakachan_js",
      description: {
        en: "Software engineer based in tokyo.",
        ja: "東京を拠点に活動するソフトウェアエンジニア。",
      },
    },
    {
      id: "taroj1205",
      name: { en: "Shintaro Jokagi", ja: "Shintaro Jokagi" },
      icon: "https://avatars.githubusercontent.com/u/61367823?v=4",
      github: "https://github.com/taroj1205",
      twitter: "https://twitter.com/taroj1205",
      description: {
        en: "Passionate about web development and a student at the University of Auckland.",
        ja: "ウェブ開発に情熱を持つオークランド大学の学生。",
      },
    },
    {
      id: "koralle",
      name: {
        en: "koralle",
        ja: "koralle",
      },
      icon: "https://avatars.githubusercontent.com/u/33865215?v=4",
      github: "https://github.com/koralle",
      twitter: "https://twitter.com/koralle_tech",
      description: {
        en: "Front-end engineer, likes React and Neovim.",
        ja: "ReactとNeovimが好きなフロントエンドエンジニア。",
      },
    },
    {
      id: "setodeve",
      name: { en: "Kei Setoguchi", ja: "Kei Setoguchi" },
      icon: "https://avatars.githubusercontent.com/u/83833293?v=4",
      github: "https://github.com/setodeve",
      twitter: "https://twitter.com/hjuko00",
      description: {
        en: "Engineer based in Fukuoka.",
        ja: "福岡在住のエンジニア。",
      },
    },
  ],
  MEMBERS: [
    {
      id: "suzukisan22",
      name: { en: "Ryota Suzuki", ja: "Ryota Suzuki" },
      icon: "https://avatars.githubusercontent.com/u/12987013?v=4",
      github: "https://github.com/suzukisan22",
      twitter: "https://x.com/itsmeryota",
      description: {
        en: "Engineer living in Mie Prefecture, Japan.",
        ja: "三重県在住エンジニア。",
      },
    },
    {
      id: "hoshico",
      name: { en: "hoshico", ja: "hoshico" },
      icon: "https://avatars.githubusercontent.com/u/77495217?v=4",
      github: "https://github.com/hoshico",
      twitter: "https://twitter.com/hoshihoshi_yasu",
      description: {
        en: "Web engineer, likes TypeScript.",
        ja: "TypeScriptが好きなWebエンジニア。",
      },
    },
    {
      id: "cidkumagai",
      name: { en: "Kazuhiro Kumagai", ja: "Kazuhiro Kumagai" },
      icon: "https://avatars.githubusercontent.com/u/78473460?v=4",
      github: "https://github.com/cidkumagai",
      description: {
        en: "Self-proclaimed front-end engineer.",
        ja: "自称フロントエンドエンジニア。",
      },
    },
    {
      id: "yasmro",
      name: { en: "Yu Ohno", ja: "Yu Ohno" },
      icon: "https://avatars.githubusercontent.com/u/30785878?v=4",
      github: "https://github.com/yasmro",
      description: {
        en: "Front-end engineer, interested in UI design and calligraphy.",
        ja: "フロントエンドとUIデザイン・書道に興味があるエンジニア。",
      },
    },
    {
      id: "fffk10",
      name: { en: "Keiju Fujiwara", ja: "Keiju Fujiwara" },
      icon: "https://avatars.githubusercontent.com/u/77735745?v=4",
      github: "https://github.com/fffk10",
      twitter: "https://twitter.com/w_q_r_q",
      description: {
        en: "Back-end engineer currently studying front-end engineering.",
        ja: "フロント勉強中の普段はバックエンドエンジニア。",
      },
    },
    {
      id: "quantumshiro",
      name: { en: "Hiro Nakanishi", ja: "Hiro Nakanishi" },
      icon: "https://avatars.githubusercontent.com/u/75029815?v=4",
      github: "https://github.com/quantumshiro",
      twitter: "https://x.com/Curiosi46542428",
      description: {
        en: "Security and machine learning engineer.",
        ja: "セキュリティと機械学習エンジニア。",
      },
    },
    {
      id: "hirayamahiroto",
      name: { en: "Hirayama Hiroto", ja: "Hirayama Hiroto" },
      icon: "https://avatars.githubusercontent.com/u/123345463?s=96&v=4",
      github: "https://github.com/hirayamahiroto",
      twitter: "https://x.com/hirotobeat",
      description: {
        en: "Web engineer.",
        ja: "Webエンジニア。",
      },
    },
    {
      id: "ayanami77",
      name: { en: "Seiya Tagami", ja: "Seiya Tagami" },
      icon: "https://avatars.githubusercontent.com/u/107479598?v=4",
      github: "https://github.com/ayanami77",
      twitter: "",
      description: {
        en: "University student interested in web development.",
        ja: "Webに興味がある大学生。",
      },
    },
    {
      id: "Haru-0001",
      name: { en: "Haruki Maeda", ja: "Haruki Maeda" },
      icon: "https://avatars.githubusercontent.com/u/166319111?v=4",
      github: "https://github.com/Haru-0001",
      twitter: "",
      description: {
        en: "Engineer based in tokyo.",
        ja: "東京のエンジニア。",
      },
    },
    {
      id: "Neru-Neru",
      name: { en: "Yuma Adachi", ja: "Yuma Adachi" },
      icon: "https://avatars.githubusercontent.com/u/56689497?v=4",
      github: "https://github.com/Neru-Neru",
      twitter: "https://twitter.com/neruneer",
      description: {
        en: "Front-end engineer.",
        ja: "フロントエンドエンジニア。",
      },
    },
    {
      id: "Tomoya-Matsubara",
      name: { en: "Tomoya Matsubara", ja: "Tomoya Matsubara" },
      icon: "https://avatars.githubusercontent.com/u/92769722?v=4",
      github: "https://github.com/Tomoya-Matsubara",
      twitter: "",
      description: {
        en: "From Web development to machine learning.",
        ja: "Web開発から機械学習まで何でもやるエンジニア。",
      },
    },
    {
      id: "kryota-dev",
      name: { en: "Ryota Kaneko", ja: "Ryota Kaneko" },
      icon: "https://avatars.githubusercontent.com/u/50436249?v=4",
      github: "https://github.com/kryota-dev",
      twitter: "https://x.com/ryotaneko827",
      description: {
        en: "Front-end engineer.",
        ja: "フロントエンドエンジニア。",
      },
    },
    {
      id: "yamao-latte",
      name: { en: "Takahiro Okuyama", ja: "Okuyama Takahiro" },
      icon: "https://avatars.githubusercontent.com/u/50776036?v=4",
      github: "https://github.com/yamao-latte",
      twitter: "https://twitter.com/shoumetsuto",
      description: {
        en: "I am a web engineer in the finance industry, currently studying front-end development and CI.",
        ja: "金融系のWebエンジニア。フロントエンドやCI系を勉強中。",
      },
    },
    {
      id: "haru-036",
      name: { en: "Haru", ja: "Haru" },
      icon: "https://avatars.githubusercontent.com/u/105186692?v=4",
      github: "https://github.com/haru-036",
      twitter: "https://twitter.com/haru_u_de",
      description: {
        en: "University students studying programming and design.",
        ja: "プログラミングとデザインを学んでいる大学生。",
      },
    },
    {
      id: "zonoryo17",
      name: { en: "Ryota Nakazono", ja: "Ryota Nakazono" },
      icon: "https://avatars.githubusercontent.com/u/88890984?v=4",
      github: "https://github.com/zonoryo17",
      twitter: "https://x.com/zonoryo03",
      description: {
        en: "Front-end engineer, developing web applications.",
        ja: "フロントエンドエンジニア。Webアプリケーションの開発を行っている。",
      },
    },
    {
      id: "harutsuka",
      name: { en: "Haruna Tsukada", ja: "Haruna Tsukada" },
      icon: "https://avatars.githubusercontent.com/u/136717269?v=4",
      github: "https://github.com/harutsuka",
      twitter: "https://twitter.com/lit_haru",
      description: {
        en: "Web engineer, a technical college student.",
        ja: "Webを学んでいる高専生。",
      },
    },
    {
      id: "kurakke",
      name: { en: "Kurakake Kaito", ja: "Kurakake Kaito" },
      icon: "https://avatars.githubusercontent.com/u/84614038?v=4",
      github: "https://github.com/kurakke",
      twitter: "https://twitter.com/kurakke",
      description: {
        en: "A student engineer who enjoys front-end and back-end development.",
        ja: "フロントエンドとバックエンドを楽しむ学生エンジニア。",
      },
    },
    {
      id: "Hayato1031",
      name: { en: "Hayato Nakamura", ja: "Hayato Nakamura" },
      icon: "https://avatars.githubusercontent.com/u/105223982?v=4",
      github: "https://github.com/Hayato1031",
      twitter: "https://twitter.com/lit_myura",
      description: {
        en: "A college student who enjoys teaching programming to middle and high school students.",
        ja: "中高生にプログラミングを教えることを楽しんでいる大学生。",
      },
    },
  ],
}
