name: "Bug Report"
description: "Create a bug report."
labels: ["triage"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating an issue 😎!

        Please search open/closed issues before submitting. Someone might have asked the same thing before 😎!

          - [Issues](https://github.com/yamada-ui/yamada-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
          - [Closed Issues](https://github.com/yamada-ui/yamada-ui/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
          - [Discussions](https://github.com/yamada-ui/yamada-ui/discussions)

        We're all volunteers here, so please help us help you by taking the time to accurately fill out this template. 💖
  - type: dropdown
    id: package
    attributes:
      label: Which package has an issue?
      options:
        - "@yamada-ui/react"
        - "@yamada-ui/cli"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Package Version"
      description: "The version of the package you are using."
      placeholder: "2.0.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A brief description of the issue."
      placeholder: |
        When I ____, I expected ____ to happen, but ____ happened instead.
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: "Link to Reproduction"
      description: |
        If possible, please include a link to a CodeSandbox with a minimal reproduction (see https://github.com/yamada-ui/yamada-ui#codesandbox for templates)
      placeholder: "https://codesandbox.io/"
  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: |
        Explain how to reproduce the issue in the provided reproduction.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: dropdown
    id: browser-type
    attributes:
      label: Browser
      description: Select the browsers where the issue can be reproduced.
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Opera"
        - "Other (add additional context)"
  - type: checkboxes
    id: operating-system
    attributes:
      label: "Operating System"
      description: "The operating system(s) on which this issue occurred."
      options:
        - label: "macOS"
        - label: "Windows"
        - label: "Linux"
        - label: "iPadOS"
        - label: "iOS"
        - label: "Android"
  - type: dropdown
    id: fix
    attributes:
      label: Do you know how to fix the issue?
      options:
        - "Yes"
        - "No"
  - type: dropdown
    id: participate
    attributes:
      label: Are you willing to participate in fixing this issue and create a pull request with the fix?
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: additional-information
    attributes:
      label: "Additional Information"
      description: |
        Use this section to provide any additional information you might have,
        such as a possible fix, screenshots, notes, or links to ideas.
  - type: markdown
    attributes:
      value: |
        This issue will be automatically unassigned after two weeks have passed since it was assigned.
        Once unassigned, it may be picked up by someone else for work.
