name: "Documentation Request"
description: "Propose new documentation requests or improvements."
labels: ["documentation", "triage"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a documentation request 😎!

        If you have an idea for a new documentation topic or noticed that something is not properly documented, you're in the right place!
  - type: input
    id: subject
    attributes:
      label: "Subject"
      description: "What is the subject (component, function, topic) of this request?"
      placeholder: "DatePicker"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What about the subject's documentation should be added or changed?"
      placeholder: "Add a usage example of `DatePicker`` in action."
    validations:
      required: true
  - type: dropdown
    id: participate
    attributes:
      label: Are you willing to participate in creating this documentation page and create a pull request?
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: ai-used
    attributes:
      label: "AI used"
      options:
        - label: "I did not use AI to create this issue."
        - label: "(If there is no check above) I checked the generated content before submitting."
  - type: markdown
    attributes:
      value: |
        This issue will be automatically unassigned after one week has passed since it was assigned.
        Once unassigned, it may be picked up by someone else for work.
