name: "Update www"
description: "Update the www site after the release"

runs:
  using: composite
  steps:
    - name: Fetch latest from origin
      run: git fetch origin
      shell: bash

    - name: Update www
      run: |
        pnpm www gen:icons
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.GITHUB_TOKEN }}
        base: main
        commit-message: "ci(changesets): update documentation"
        title: "Update documentation"
        branch: www
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
