name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git user
      shell: bash
      run: |
        git config --global user.email "hirotomo.yamada@avap.co.jp"
        git config --global user.name "hirotomoyamada"

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
