name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@8b2eead6074fefa43a68bf4c9e0f03ea4126b5ba # v6.0.3

    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup Git user
      shell: bash
      run: |
        git config --global user.email "hirotomo.yamada@avap.co.jp"
        git config --global user.name "hirotomoyamada"

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts
