name: "Sync docs"
description: "Sync the documentation sites after the release"

runs:
  using: composite
  steps:
    - name: Fetch latest from origin
      run: git fetch origin
      shell: bash

    - name: Sync docs
      run: |
        pnpm gen:docs
        pnpm docs:theme
        pnpm docs:props
        pnpm docs:changelog
        pnpm docs:styled-system
        pnpm docs:contributors
        pnpm docs:search
        pnpm docs:icon-tags
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ env.GITHUB_TOKEN }}
        base: documentation
        commit-message: "ci(changesets): sync documentation"
        title: "Sync documentation"
        branch: changeset-release/docs
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
