import { Metadata } from "next"
import Home from "./home"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function HomePage() {
  return <Home />
}
