name: "Check for Modified Files"
description: "Check for modified files in specific paths"

inputs:
  paths:
    description: "File paths to check for modifications"
    required: true
outputs:
  changed:
    description: "Whether any specified files have been modified"
    value: ${{ steps.check-modified.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Fetch base branch
      run: git fetch origin ${{ github.base_ref }}
      shell: bash

    - name: Check modified files
      id: check-modified
      run: |
        changed=$(\
          git diff --name-only FETCH_HEAD ${{ github.sha }} | grep -E '^(packages/|scripts/setup-test.ts|package.json|.eslintrc.json|.eslintrc.base.json|.eslintignore|.prettierrc.json|.prettierignore|turbo.json|vitest.config.mts)')
        if [ -z "$changed" ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash
