export const ICON_TEMPLATE = [
  `"use client"`,
  ``,
  `import type { Component } from "../../../core"`,
  `import type { IconProps } from "../icon"`,
  `import { {{iconName}} as Original{{iconName}}Icon } from "lucide-react"`,
  `import { component, Icon } from "../icon"`,
  ``,
  `/**`,
  ` * \`{{iconName}}Icon\` is [Lucide](https://lucide.dev) SVG icon component.`,
  ` *`,
  ` * @see https://yamada-ui.com/docs/components/icon`,
  ` */`,
  `export const {{iconName}}Icon = component(Icon)({ as: Original{{iconName}}Icon }) as Component<"svg", IconProps>`,
  ``,
].join("\n")
