name: "Update docs"
description: "Update the documentation sites after the release"

runs:
  using: composite
  steps:
    - name: Update docs
      run: |
        pnpm gen:docs
        pnpm docs:theme
        pnpm docs:props
        pnpm docs:changelog
        pnpm docs:css
        pnpm docs:contributors
        pnpm docs:search
      shell: bash

    - name: Create PR
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ env.GITHUB_TOKEN }}
        base: main
        commit-message: "ci(changesets): version packages"
        title: "Updated dependencies"
        branch: changeset-release/docs
        assignees: "hirotomoyamada"
        reviewers: "hirotomoyamada"
