export type {
  HTMLMotionProps,
  SVGMotionProps,
  Variants as MotionVariants,
  AnimatePresenceProps as MotionAnimatePresenceProps,
  LayoutProps as MotionLayoutProps,
  LazyProps as MotionLazyProps,
  MotionConfigProps,
  AnimationControls as MotionAnimationControls,
  AnimationProps as MotionAnimationProps,
  AnimationType as MotionAnimationType,
  AnimationLifecycles as MotionAnimationLifecycles,
  AnimationOptions as MotionAnimationOptions,
  AnimationPlaybackControls as MotionAnimationPlaybackControls,
} from 'framer-motion'
export {
  motion,
  AnimatePresence,
  LayoutGroup,
  LazyMotion,
  MotionConfig,
  Reorder,
  useMotionTemplate,
  useScroll,
  useSpring,
  useTime,
  useTransform,
  useVelocity,
  useViewportScroll,
  useAnimation as useMotionAnimation,
  useAnimationControls as useMotionAnimationControls,
  useAnimationFrame as useMotionAnimationFrame,
  useDragControls,
  useInView,
  useReducedMotion,
} from 'framer-motion'

export * from './Motion'
