name: Codecov

on:
  push:
    paths:
      - ".github/workflows/codecov.yml"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "codecov.yml"
      - "packages/cli/package.json"
      - "packages/cli/vitest.config.ts"
      - "packages/cli/src/**/*.ts"
      - "packages/cli/src/**/*.tsx"
      - "packages/cli/test/**/*"
      - "packages/react/package.json"
      - "packages/react/vitest.config.ts"
      - "packages/react/src/**/*.ts"
      - "packages/react/src/**/*.tsx"
      - "packages/react/test/**/*"
      - "packages/utils/package.json"
      - "packages/utils/vitest.config.ts"
      - "packages/utils/src/**/*.ts"
      - "packages/utils/src/**/*.tsx"
      - "packages/workspace/package.json"
      - "packages/workspace/src/vitest/**/*"
      - "!packages/**/*.stories.ts"
      - "!packages/**/*.stories.tsx"
    branches:
      - main

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  unit_test:
    name: Unit Test
    uses: ./.github/workflows/unit-test.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  browser_test:
    name: Browser Test
    uses: ./.github/workflows/browser-test.yml
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
