name: Create PR for docs

on:
  push:
    branches:
      - documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for existing PR
        id: check_pr
        run: |
          pr_exists=$(gh pr list --base main --head documentation --json number --jq 'length')
          if [ "$pr_exists" -eq 0 ]; then
            echo "pr_exists=false" >> $GITHUB_OUTPUT
          else
            echo "pr_exists=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin main
          changes=$(git diff --name-only origin/main)
          if [ -z "$changes" ]; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create PR
        if: steps.check_pr.outputs.pr_exists == 'false' && steps.check_changes.outputs.changes == 'true'
        run: |
          gh pr create --base main --head documentation --title "Updated documentation" --body "Automated changes by GitHub action" --reviewer hirotomoyamada --assignee hirotomoyamada
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
