name: Insights Upload

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  insight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Create insight report
        run: |
          yesterday=$(date -d '+9 hours -1 day' '+%Y-%m-%d')
          pnpm report:insights -s $yesterday -e $yesterday --upload
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          DISCORD_INSIGHTS_WEBHOOK_URL: ${{ secrets.DISCORD_INSIGHTS_WEBHOOK_URL }}
