name: Post Dependabot

on:
  pull_request:
    types: [opened]
    branches:
      - "dependabot/npm_and_yarn/**"

jobs:
  hoge:
    name: Hoge
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install
        if: steps.check-modified.outputs.any_changed == 'true'
        uses: ./.github/composite-actions/install
