name: Storybook

on:
  push:
    paths:
      - ".github/workflows/storybook.yml"
      - "package.json"
      - "pnpm-workspace.yaml"
      - "packages/react/package.json"
      - "packages/react/src/**/*.ts"
      - "packages/react/src/**/*.tsx"
      - "packages/react/storybook/**/*"
      - "packages/utils/package.json"
      - "packages/utils/src/**/*.ts"
      - "packages/utils/src/**/*.tsx"
      - "!packages/**/*.test.ts"
      - "!packages/**/*.test.*.ts"
      - "!packages/**/*.test.tsx"
      - "!packages/**/*.test.*.tsx"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build Storybook
        run: pnpm react storybook:build

      - name: Insert ignored-build-step.sh
        run: |
          dir="packages/react/storybook-static/www"
          mkdir -p "$dir" && touch "$dir/ignored-build-step.sh"
          echo "exit 0" > "$dir/ignored-build-step.sh"

      - name: Update Storybook
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: packages/react/storybook-static
          clean: true
          clean-exclude: .nojekyll
